# Generated by Django 1.10.4 on 2021-04-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]